/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as AppLayoutRouteImport } from "./routes/_appLayout";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AppLayoutIndexRouteImport } from "./routes/_appLayout/index";
import { Route as DashboardPollsRouteImport } from "./routes/dashboard/polls";
import { Route as DashboardAnalyticsRouteImport } from "./routes/dashboard/analytics";
import { Route as AppLayoutPollRouteImport } from "./routes/_appLayout/poll";
import { Route as AppLayoutContactRouteImport } from "./routes/_appLayout/contact";
import { Route as AppLayoutAboutRouteImport } from "./routes/_appLayout/about";
import { Route as docsDocsRouteImport } from "./routes/(docs)/docs";
import { Route as AppLayoutPollIndexRouteImport } from "./routes/_appLayout/poll/index";
import { Route as AppLayoutPollCreateRouteImport } from "./routes/_appLayout/poll/create";
import { Route as AppLayoutPollPollIdRouteImport } from "./routes/_appLayout/poll/$pollId";
import { Route as AppLayoutauthSignupRouteImport } from "./routes/_appLayout/(auth)/signup";
import { Route as AppLayoutauthSigninRouteImport } from "./routes/_appLayout/(auth)/signin";

const DashboardRoute = DashboardRouteImport.update({
    id: "/dashboard",
    path: "/dashboard",
    getParentRoute: () => rootRouteImport,
} as any);
const AppLayoutRoute = AppLayoutRouteImport.update({
    id: "/_appLayout",
    getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardRoute,
} as any);
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppLayoutRoute,
} as any);
const DashboardPollsRoute = DashboardPollsRouteImport.update({
    id: "/polls",
    path: "/polls",
    getParentRoute: () => DashboardRoute,
} as any);
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
    id: "/analytics",
    path: "/analytics",
    getParentRoute: () => DashboardRoute,
} as any);
const AppLayoutPollRoute = AppLayoutPollRouteImport.update({
    id: "/poll",
    path: "/poll",
    getParentRoute: () => AppLayoutRoute,
} as any);
const AppLayoutContactRoute = AppLayoutContactRouteImport.update({
    id: "/contact",
    path: "/contact",
    getParentRoute: () => AppLayoutRoute,
} as any);
const AppLayoutAboutRoute = AppLayoutAboutRouteImport.update({
    id: "/about",
    path: "/about",
    getParentRoute: () => AppLayoutRoute,
} as any);
const docsDocsRoute = docsDocsRouteImport.update({
    id: "/(docs)/docs",
    path: "/docs",
    getParentRoute: () => rootRouteImport,
} as any);
const AppLayoutPollIndexRoute = AppLayoutPollIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppLayoutPollRoute,
} as any);
const AppLayoutPollCreateRoute = AppLayoutPollCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => AppLayoutPollRoute,
} as any);
const AppLayoutPollPollIdRoute = AppLayoutPollPollIdRouteImport.update({
    id: "/$pollId",
    path: "/$pollId",
    getParentRoute: () => AppLayoutPollRoute,
} as any);
const AppLayoutauthSignupRoute = AppLayoutauthSignupRouteImport.update({
    id: "/(auth)/signup",
    path: "/signup",
    getParentRoute: () => AppLayoutRoute,
} as any);
const AppLayoutauthSigninRoute = AppLayoutauthSigninRouteImport.update({
    id: "/(auth)/signin",
    path: "/signin",
    getParentRoute: () => AppLayoutRoute,
} as any);

export interface FileRoutesByFullPath {
    "/": typeof AppLayoutIndexRoute;
    "/dashboard": typeof DashboardRouteWithChildren;
    "/docs": typeof docsDocsRoute;
    "/about": typeof AppLayoutAboutRoute;
    "/contact": typeof AppLayoutContactRoute;
    "/poll": typeof AppLayoutPollRouteWithChildren;
    "/dashboard/analytics": typeof DashboardAnalyticsRoute;
    "/dashboard/polls": typeof DashboardPollsRoute;
    "/dashboard/": typeof DashboardIndexRoute;
    "/signin": typeof AppLayoutauthSigninRoute;
    "/signup": typeof AppLayoutauthSignupRoute;
    "/poll/$pollId": typeof AppLayoutPollPollIdRoute;
    "/poll/create": typeof AppLayoutPollCreateRoute;
    "/poll/": typeof AppLayoutPollIndexRoute;
}
export interface FileRoutesByTo {
    "/docs": typeof docsDocsRoute;
    "/about": typeof AppLayoutAboutRoute;
    "/contact": typeof AppLayoutContactRoute;
    "/dashboard/analytics": typeof DashboardAnalyticsRoute;
    "/dashboard/polls": typeof DashboardPollsRoute;
    "/": typeof AppLayoutIndexRoute;
    "/dashboard": typeof DashboardIndexRoute;
    "/signin": typeof AppLayoutauthSigninRoute;
    "/signup": typeof AppLayoutauthSignupRoute;
    "/poll/$pollId": typeof AppLayoutPollPollIdRoute;
    "/poll/create": typeof AppLayoutPollCreateRoute;
    "/poll": typeof AppLayoutPollIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    "/_appLayout": typeof AppLayoutRouteWithChildren;
    "/dashboard": typeof DashboardRouteWithChildren;
    "/(docs)/docs": typeof docsDocsRoute;
    "/_appLayout/about": typeof AppLayoutAboutRoute;
    "/_appLayout/contact": typeof AppLayoutContactRoute;
    "/_appLayout/poll": typeof AppLayoutPollRouteWithChildren;
    "/dashboard/analytics": typeof DashboardAnalyticsRoute;
    "/dashboard/polls": typeof DashboardPollsRoute;
    "/_appLayout/": typeof AppLayoutIndexRoute;
    "/dashboard/": typeof DashboardIndexRoute;
    "/_appLayout/(auth)/signin": typeof AppLayoutauthSigninRoute;
    "/_appLayout/(auth)/signup": typeof AppLayoutauthSignupRoute;
    "/_appLayout/poll/$pollId": typeof AppLayoutPollPollIdRoute;
    "/_appLayout/poll/create": typeof AppLayoutPollCreateRoute;
    "/_appLayout/poll/": typeof AppLayoutPollIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | "/"
        | "/dashboard"
        | "/docs"
        | "/about"
        | "/contact"
        | "/poll"
        | "/dashboard/analytics"
        | "/dashboard/polls"
        | "/dashboard/"
        | "/signin"
        | "/signup"
        | "/poll/$pollId"
        | "/poll/create"
        | "/poll/";
    fileRoutesByTo: FileRoutesByTo;
    to:
        | "/docs"
        | "/about"
        | "/contact"
        | "/dashboard/analytics"
        | "/dashboard/polls"
        | "/"
        | "/dashboard"
        | "/signin"
        | "/signup"
        | "/poll/$pollId"
        | "/poll/create"
        | "/poll";
    id:
        | "__root__"
        | "/_appLayout"
        | "/dashboard"
        | "/(docs)/docs"
        | "/_appLayout/about"
        | "/_appLayout/contact"
        | "/_appLayout/poll"
        | "/dashboard/analytics"
        | "/dashboard/polls"
        | "/_appLayout/"
        | "/dashboard/"
        | "/_appLayout/(auth)/signin"
        | "/_appLayout/(auth)/signup"
        | "/_appLayout/poll/$pollId"
        | "/_appLayout/poll/create"
        | "/_appLayout/poll/";
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    AppLayoutRoute: typeof AppLayoutRouteWithChildren;
    DashboardRoute: typeof DashboardRouteWithChildren;
    docsDocsRoute: typeof docsDocsRoute;
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/dashboard": {
            id: "/dashboard";
            path: "/dashboard";
            fullPath: "/dashboard";
            preLoaderRoute: typeof DashboardRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/_appLayout": {
            id: "/_appLayout";
            path: "";
            fullPath: "/";
            preLoaderRoute: typeof AppLayoutRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/dashboard/": {
            id: "/dashboard/";
            path: "/";
            fullPath: "/dashboard/";
            preLoaderRoute: typeof DashboardIndexRouteImport;
            parentRoute: typeof DashboardRoute;
        };
        "/_appLayout/": {
            id: "/_appLayout/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof AppLayoutIndexRouteImport;
            parentRoute: typeof AppLayoutRoute;
        };
        "/dashboard/polls": {
            id: "/dashboard/polls";
            path: "/polls";
            fullPath: "/dashboard/polls";
            preLoaderRoute: typeof DashboardPollsRouteImport;
            parentRoute: typeof DashboardRoute;
        };
        "/dashboard/analytics": {
            id: "/dashboard/analytics";
            path: "/analytics";
            fullPath: "/dashboard/analytics";
            preLoaderRoute: typeof DashboardAnalyticsRouteImport;
            parentRoute: typeof DashboardRoute;
        };
        "/_appLayout/poll": {
            id: "/_appLayout/poll";
            path: "/poll";
            fullPath: "/poll";
            preLoaderRoute: typeof AppLayoutPollRouteImport;
            parentRoute: typeof AppLayoutRoute;
        };
        "/_appLayout/contact": {
            id: "/_appLayout/contact";
            path: "/contact";
            fullPath: "/contact";
            preLoaderRoute: typeof AppLayoutContactRouteImport;
            parentRoute: typeof AppLayoutRoute;
        };
        "/_appLayout/about": {
            id: "/_appLayout/about";
            path: "/about";
            fullPath: "/about";
            preLoaderRoute: typeof AppLayoutAboutRouteImport;
            parentRoute: typeof AppLayoutRoute;
        };
        "/(docs)/docs": {
            id: "/(docs)/docs";
            path: "/docs";
            fullPath: "/docs";
            preLoaderRoute: typeof docsDocsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/_appLayout/poll/": {
            id: "/_appLayout/poll/";
            path: "/";
            fullPath: "/poll/";
            preLoaderRoute: typeof AppLayoutPollIndexRouteImport;
            parentRoute: typeof AppLayoutPollRoute;
        };
        "/_appLayout/poll/create": {
            id: "/_appLayout/poll/create";
            path: "/create";
            fullPath: "/poll/create";
            preLoaderRoute: typeof AppLayoutPollCreateRouteImport;
            parentRoute: typeof AppLayoutPollRoute;
        };
        "/_appLayout/poll/$pollId": {
            id: "/_appLayout/poll/$pollId";
            path: "/$pollId";
            fullPath: "/poll/$pollId";
            preLoaderRoute: typeof AppLayoutPollPollIdRouteImport;
            parentRoute: typeof AppLayoutPollRoute;
        };
        "/_appLayout/(auth)/signup": {
            id: "/_appLayout/(auth)/signup";
            path: "/signup";
            fullPath: "/signup";
            preLoaderRoute: typeof AppLayoutauthSignupRouteImport;
            parentRoute: typeof AppLayoutRoute;
        };
        "/_appLayout/(auth)/signin": {
            id: "/_appLayout/(auth)/signin";
            path: "/signin";
            fullPath: "/signin";
            preLoaderRoute: typeof AppLayoutauthSigninRouteImport;
            parentRoute: typeof AppLayoutRoute;
        };
    }
}

interface AppLayoutPollRouteChildren {
    AppLayoutPollPollIdRoute: typeof AppLayoutPollPollIdRoute;
    AppLayoutPollCreateRoute: typeof AppLayoutPollCreateRoute;
    AppLayoutPollIndexRoute: typeof AppLayoutPollIndexRoute;
}

const AppLayoutPollRouteChildren: AppLayoutPollRouteChildren = {
    AppLayoutPollPollIdRoute: AppLayoutPollPollIdRoute,
    AppLayoutPollCreateRoute: AppLayoutPollCreateRoute,
    AppLayoutPollIndexRoute: AppLayoutPollIndexRoute,
};

const AppLayoutPollRouteWithChildren = AppLayoutPollRoute._addFileChildren(
    AppLayoutPollRouteChildren
);

interface AppLayoutRouteChildren {
    AppLayoutAboutRoute: typeof AppLayoutAboutRoute;
    AppLayoutContactRoute: typeof AppLayoutContactRoute;
    AppLayoutPollRoute: typeof AppLayoutPollRouteWithChildren;
    AppLayoutIndexRoute: typeof AppLayoutIndexRoute;
    AppLayoutauthSigninRoute: typeof AppLayoutauthSigninRoute;
    AppLayoutauthSignupRoute: typeof AppLayoutauthSignupRoute;
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
    AppLayoutAboutRoute: AppLayoutAboutRoute,
    AppLayoutContactRoute: AppLayoutContactRoute,
    AppLayoutPollRoute: AppLayoutPollRouteWithChildren,
    AppLayoutIndexRoute: AppLayoutIndexRoute,
    AppLayoutauthSigninRoute: AppLayoutauthSigninRoute,
    AppLayoutauthSignupRoute: AppLayoutauthSignupRoute,
};

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
    AppLayoutRouteChildren
);

interface DashboardRouteChildren {
    DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute;
    DashboardPollsRoute: typeof DashboardPollsRoute;
    DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
    DashboardAnalyticsRoute: DashboardAnalyticsRoute,
    DashboardPollsRoute: DashboardPollsRoute,
    DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
    DashboardRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
    AppLayoutRoute: AppLayoutRouteWithChildren,
    DashboardRoute: DashboardRouteWithChildren,
    docsDocsRoute: docsDocsRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();
