name: commit-lint
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install commitlint ruleset
        run: pnpm add -D @commitlint/config-conventional

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          pnpm dlx commitlint --from=origin/${{ github.event.pull_request.base.ref }} --to=HEAD --verbose